### ISSUE TITLE
Hex checksum should be lowercase

### ISSUE THREAD

**Issue by sunny-lan** [stef/pyrsp#16]
I believe in `utils.py`, inside function `pack`, line 129

```
res += b"#%02X" % (_sum & 0xff)
```

This should instead be changed to `%02x`

I tried the library with gdbserver and I get `Invalid hex digit` unless I make this change.

**Comment by stef** [comment]
strange, which gdbserver did you try this with?

**Comment by sunny-lan** [comment]
GNU gdbserver (GDB) 7.6.1

I'm using Windows and gdbserver was included with mingw32.

**Comment by stef** [comment]
hmmmm, still strange. but ok.
