### ISSUE TITLE
Confusing example in README

### ISSUE THREAD

**Issue by reverendhomer** [stef/pyrsp#3]
Hi!

With script

``` python
from pyrsp.rsp import RSP
rsp = RSP(3333, '/path/to/filename')
```

I'm getting this error

```
  File "/home/user/.local/lib/python2.7/site-packages/pyrsp/rsp.py", line 185, in __getattr__
    if name in self.regs.keys():
  File "/home/user/.local/lib/python2.7/site-packages/pyrsp/rsp.py", line 185, in __getattr__
    if name in self.regs.keys():
  File "/home/user/.local/lib/python2.7/site-packages/pyrsp/rsp.py", line 185, in __getattr__
    if name in self.regs.keys():
  File "/home/user/.local/lib/python2.7/site-packages/pyrsp/rsp.py", line 185, in __getattr__
    if name in self.regs.keys():
  File "/home/user/.local/lib/python2.7/site-packages/pyrsp/rsp.py", line 185, in __getattr__
    if name in self.regs.keys():
RuntimeError: maximum recursion depth exceeded
```

After cursory looking into the code, I've found [this](https://github.com/stef/pyrsp/blob/master/pyrsp/rsp.py#L94):

``` python
    def __init__(self, port, elffile=None, verbose=False):
        """ read the elf file if given by elffile, connects to the
            debugging device specified by port, and initializes itself.
        """
        self.registers = self.arch['regs']
```

but there's no self.arch out there. Maybe this is causing infinite recursion.

Can you help me with this issue?

**Comment by stef** [comment]
have a look here: https://github.com/stef/pyrsp/blob/master/pyrsp/rsp.py#L556 which shows how to instantiate an arch. 
basically  you import from rsp AMD64, i386, CortexM3 and instantiate one of them, each being a sub-class of the RSP class.
hope this helps.

**Comment by reverendhomer** [comment]
Yeah, thanks, I got it just after opening this issue. So I think primary issue was caused by confusing example in README:
```python
from rsp import RSP
rsp = RSP('/dev/ttyACM0', 'test.elf') # expects test.elf to exist
rsp.load() # load test.elf into workarea (.text segment)
```

**Comment by stef** [comment]
uh, right. will update it!

**Comment by stef** [comment]
i am very embarrassed this took so long. please accept my apologies for forgetting about this.
