### ISSUE TITLE
Construct was updated - A LOT

### ISSUE THREAD

**Issue by dor-zusman** [stef/pyrsp#7]
Nothing works anymore :(

**Comment by stef** [comment]
damn. is there a reason to upgrade to the latest, or is it enough to pin the version to an older version that still works?

**Comment by dor-zusman** [comment]
The right solution will be to upgrade to the latest Construct, but pinning a version is also fine :)
Thanks!

**Comment by stef** [comment]
i'll have a look at it

**Comment by stef** [comment]
@dor-zusman can you confirm this https://github.com/stef/pyrsp/pull/8 fixes your report?
